name: run-tests
on: [push, pull_request]
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        luaVersion: ["5.1.3", "5.1.4", "5.1.5", "5.2.2", "5.2.3", "5.2.4", "5.3.0", "5.3.1", "5.3.2", "5.3.3", "5.3.4", "5.3.5", "5.3.6", "5.4.0", "5.4.1"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: leafo/gh-actions-lua@v7
        with:
          luaVersion: ${{ matrix.luaVersion }}
      - uses: leafo/gh-actions-luarocks@v3
      - run: luarocks make CFLAGS="-Wall -Wextra -O2 -fPIC"
      - run: lua tests/test.lua

