name: run-tests
on:
  push:
    branches: ["master"]
  pull_request:
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        luaVersion:
          - "5.1.3"
          - "5.1.4"
          - "5.1.5"
          - "5.2.2"
          - "5.2.3"
          - "5.2.4"
          - "5.3.4"
          - "5.3.5"
          - "5.3.6"
          - "5.4.0"
          - "5.4.1"
          - "5.4.2"
          - "5.4.3"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: leafo/gh-actions-lua@v8
        with:
          luaVersion: ${{ matrix.luaVersion }}
      - uses: leafo/gh-actions-luarocks@v4
      - run: luarocks make CFLAGS="-Wall -Wextra -O2 -fPIC"
      - run: lua tests/test.lua

